import type { Metadata } from 'next'
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'My App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <header className="flex justify-end items-center p-4 gap-2 h-16">
                        {/* Show the sign-in and sign-up buttons when the user is signed out */}
                        <SignedOut>
                            <SignInButton>
                                <button className="btn btn-sm rounded-none hover:brightness-110 transition">
                                    Sign In
                                </button>
                            </SignInButton>
                            <SignUpButton>
                                <button className="btn btn-sm bg-[#6c47ff] text-white rounded-none hover:brightness-110 transition">
                                    Sign Up
                                </button>
                            </SignUpButton>
                        </SignedOut>
                        {/* Show the user button when the user is signed in */}
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                    </header>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
